add times related
everdale-wiki/wiki pull request #1
Opened 2021-10-04 07:38 UTC by fanweixiao

2021-10-05 21:54 UTC, everdale-wiki requested changes

2021-10-05 21:54 UTC, everdale-wiki commented on time.md
> +# Time per item
The heading should be in title case.
```suggestion
# Time Per Item
```

2021-10-05 21:54 UTC, everdale-wiki commented on time.md
> +Villager's hunger time: 2m30s
This should be title case as well, along with an emphasis.
```suggestion
**Villager's Hunger Time:** 2m30s
```

2021-10-05 21:57 UTC, everdale-wiki commented
Thanks a lot for this pull request!

In addition to the above changes, could you please also reference this page in the [`README.md`]? The `README.md` is the index page of the website and is the only way to navigate to other pages at the moment.

2021-10-06 03:57 UTC, fanweixiao commented
Yes, I've added this page to the index in `README.md`.

2021-10-06 16:53 UTC, merged